name: PushDockerImage

on:
  push:
    branches:
    - master

jobs:
  docker_image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sigbilly/github-action-pull-request-size:latest
    - name: Login to Docker hub
      run: docker login -u sigbilly -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Push the Docker image
      run: docker push sigbilly/github-action-pull-request-size:latest
  update_docker_hub_doc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Update Docker hub documentation
      uses: docker://mpepping/docker-hub-metadata-github-action
      env:
        IMAGE: sigbilly/github-action-pull-request-size
        DOCKER_USERNAME: sigbilly
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}